GET http://localhost:8080/
###
GET http://localhost:8080/recipe/3

###
GET http://localhost:8080/info
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "Title": "пюре",
  "cookingTime": "50",
  "ingredients": [
    {
      "title": "картофель",
      "number": 400,
      "measure": "г"
    }
    ],
  "steps": [
    "Step 1",
    "Step 2",
    "Step 3"
  ]

      }
###
GET http://localhost:8080/recipe
###
GET http://localhost:8080/recipe/0