GET http://localhost:8080/
###
GET http://localhost:8080/recipe/1

###
GET http://localhost:8080/info
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "Title": "суп-пюре",
  "cookingTime": "30",
  "ingredients": [
    {
      "title": "картофель",
      "number": 300,
      "measure": "г"
    }
    ],
  "steps": [
    "Step 1",
    "Step 2",
    "Step 3"
  ]

      }
###
GET http://localhost:8080/recipe
###
GET http://localhost:8080/recipe/0
###
DELETE http://localhost:8080/recipe/1

###
GET http://localhost:8080/ingredient/
###
GET http://localhost:8080/ingredient/1
###
POST http://localhost:8080/ingredient
Content-Type: application/json


{
"title": "сыр",
"number": 300,
"measure": "мл"
}

###
DELETE http://localhost:8080/ingredient/5


